name: cpp build

on:
  push:
    branches: [ master ]

jobs:
  Win-Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: egor-tensin/setup-mingw@v2
    - shell: cmd
      run: |
        g++ Source/*.cpp -s -Os -I Include -o JKRArchiveTools.exe 
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: Win-Build
        path: |
          *.exe
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
            *.exe